"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _dashboard_base_resumes from './dashboard-base-resumes.bones.json'

registerBones({
  "dashboard-base-resumes": _dashboard_base_resumes,
})
