/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as ApiTailoredResumesIndexRouteImport } from './routes/api/tailored-resumes/index'
import { Route as ApiBaseResumeIndexRouteImport } from './routes/api/base-resume/index'
import { Route as GatewaySignUpIndexRouteImport } from './routes/_gateway/sign-up/index'
import { Route as GatewaySignInIndexRouteImport } from './routes/_gateway/sign-in/index'
import { Route as AppProfileIndexRouteImport } from './routes/_app/profile/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as ApiTailoredResumesSessionIdRouteImport } from './routes/api/tailored-resumes/$sessionId'
import { Route as ApiResumesReportIdRouteImport } from './routes/api/resumes/$reportId'
import { Route as ApiBaseResumeResumeIdRouteImport } from './routes/api/base-resume/$resumeId'
import { Route as ApiAuthVerifyOtpRouteImport } from './routes/api/auth/verify-otp'
import { Route as ApiAuthSignUpRouteImport } from './routes/api/auth/sign-up'
import { Route as ApiAuthSignInRouteImport } from './routes/api/auth/sign-in'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as AppTailoredResumesSessionIdIndexRouteImport } from './routes/_app/tailored-resumes/$sessionId/index'
import { Route as AppTailoredResumesSessionIdPreviewIndexRouteImport } from './routes/_app/tailored-resumes/$sessionId/preview/index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTailoredResumesIndexRoute = ApiTailoredResumesIndexRouteImport.update({
  id: '/api/tailored-resumes/',
  path: '/api/tailored-resumes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBaseResumeIndexRoute = ApiBaseResumeIndexRouteImport.update({
  id: '/api/base-resume/',
  path: '/api/base-resume/',
  getParentRoute: () => rootRouteImport,
} as any)
const GatewaySignUpIndexRoute = GatewaySignUpIndexRouteImport.update({
  id: '/_gateway/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const GatewaySignInIndexRoute = GatewaySignInIndexRouteImport.update({
  id: '/_gateway/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiTailoredResumesSessionIdRoute =
  ApiTailoredResumesSessionIdRouteImport.update({
    id: '/api/tailored-resumes/$sessionId',
    path: '/api/tailored-resumes/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiResumesReportIdRoute = ApiResumesReportIdRouteImport.update({
  id: '/api/resumes/$reportId',
  path: '/api/resumes/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBaseResumeResumeIdRoute = ApiBaseResumeResumeIdRouteImport.update({
  id: '/api/base-resume/$resumeId',
  path: '/api/base-resume/$resumeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthVerifyOtpRoute = ApiAuthVerifyOtpRouteImport.update({
  id: '/api/auth/verify-otp',
  path: '/api/auth/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignUpRoute = ApiAuthSignUpRouteImport.update({
  id: '/api/auth/sign-up',
  path: '/api/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInRoute = ApiAuthSignInRouteImport.update({
  id: '/api/auth/sign-in',
  path: '/api/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTailoredResumesSessionIdIndexRoute =
  AppTailoredResumesSessionIdIndexRouteImport.update({
    id: '/tailored-resumes/$sessionId/',
    path: '/tailored-resumes/$sessionId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppTailoredResumesSessionIdPreviewIndexRoute =
  AppTailoredResumesSessionIdPreviewIndexRouteImport.update({
    id: '/tailored-resumes/$sessionId/preview/',
    path: '/tailored-resumes/$sessionId/preview/',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute
  '/api/auth/verify-otp': typeof ApiAuthVerifyOtpRoute
  '/api/base-resume/$resumeId': typeof ApiBaseResumeResumeIdRoute
  '/api/resumes/$reportId': typeof ApiResumesReportIdRoute
  '/api/tailored-resumes/$sessionId': typeof ApiTailoredResumesSessionIdRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/profile/': typeof AppProfileIndexRoute
  '/sign-in/': typeof GatewaySignInIndexRoute
  '/sign-up/': typeof GatewaySignUpIndexRoute
  '/api/base-resume/': typeof ApiBaseResumeIndexRoute
  '/api/tailored-resumes/': typeof ApiTailoredResumesIndexRoute
  '/tailored-resumes/$sessionId/': typeof AppTailoredResumesSessionIdIndexRoute
  '/tailored-resumes/$sessionId/preview/': typeof AppTailoredResumesSessionIdPreviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute
  '/api/auth/verify-otp': typeof ApiAuthVerifyOtpRoute
  '/api/base-resume/$resumeId': typeof ApiBaseResumeResumeIdRoute
  '/api/resumes/$reportId': typeof ApiResumesReportIdRoute
  '/api/tailored-resumes/$sessionId': typeof ApiTailoredResumesSessionIdRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/profile': typeof AppProfileIndexRoute
  '/sign-in': typeof GatewaySignInIndexRoute
  '/sign-up': typeof GatewaySignUpIndexRoute
  '/api/base-resume': typeof ApiBaseResumeIndexRoute
  '/api/tailored-resumes': typeof ApiTailoredResumesIndexRoute
  '/tailored-resumes/$sessionId': typeof AppTailoredResumesSessionIdIndexRoute
  '/tailored-resumes/$sessionId/preview': typeof AppTailoredResumesSessionIdPreviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute
  '/api/auth/verify-otp': typeof ApiAuthVerifyOtpRoute
  '/api/base-resume/$resumeId': typeof ApiBaseResumeResumeIdRoute
  '/api/resumes/$reportId': typeof ApiResumesReportIdRoute
  '/api/tailored-resumes/$sessionId': typeof ApiTailoredResumesSessionIdRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/profile/': typeof AppProfileIndexRoute
  '/_gateway/sign-in/': typeof GatewaySignInIndexRoute
  '/_gateway/sign-up/': typeof GatewaySignUpIndexRoute
  '/api/base-resume/': typeof ApiBaseResumeIndexRoute
  '/api/tailored-resumes/': typeof ApiTailoredResumesIndexRoute
  '/_app/tailored-resumes/$sessionId/': typeof AppTailoredResumesSessionIdIndexRoute
  '/_app/tailored-resumes/$sessionId/preview/': typeof AppTailoredResumesSessionIdPreviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/legal/privacy'
    | '/legal/terms'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/auth/sign-in'
    | '/api/auth/sign-up'
    | '/api/auth/verify-otp'
    | '/api/base-resume/$resumeId'
    | '/api/resumes/$reportId'
    | '/api/tailored-resumes/$sessionId'
    | '/dashboard/'
    | '/profile/'
    | '/sign-in/'
    | '/sign-up/'
    | '/api/base-resume/'
    | '/api/tailored-resumes/'
    | '/tailored-resumes/$sessionId/'
    | '/tailored-resumes/$sessionId/preview/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/legal/privacy'
    | '/legal/terms'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/auth/sign-in'
    | '/api/auth/sign-up'
    | '/api/auth/verify-otp'
    | '/api/base-resume/$resumeId'
    | '/api/resumes/$reportId'
    | '/api/tailored-resumes/$sessionId'
    | '/dashboard'
    | '/profile'
    | '/sign-in'
    | '/sign-up'
    | '/api/base-resume'
    | '/api/tailored-resumes'
    | '/tailored-resumes/$sessionId'
    | '/tailored-resumes/$sessionId/preview'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/legal/privacy'
    | '/legal/terms'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/auth/sign-in'
    | '/api/auth/sign-up'
    | '/api/auth/verify-otp'
    | '/api/base-resume/$resumeId'
    | '/api/resumes/$reportId'
    | '/api/tailored-resumes/$sessionId'
    | '/_app/dashboard/'
    | '/_app/profile/'
    | '/_gateway/sign-in/'
    | '/_gateway/sign-up/'
    | '/api/base-resume/'
    | '/api/tailored-resumes/'
    | '/_app/tailored-resumes/$sessionId/'
    | '/_app/tailored-resumes/$sessionId/preview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiAuthSignInRoute: typeof ApiAuthSignInRoute
  ApiAuthSignUpRoute: typeof ApiAuthSignUpRoute
  ApiAuthVerifyOtpRoute: typeof ApiAuthVerifyOtpRoute
  ApiBaseResumeResumeIdRoute: typeof ApiBaseResumeResumeIdRoute
  ApiResumesReportIdRoute: typeof ApiResumesReportIdRoute
  ApiTailoredResumesSessionIdRoute: typeof ApiTailoredResumesSessionIdRoute
  GatewaySignInIndexRoute: typeof GatewaySignInIndexRoute
  GatewaySignUpIndexRoute: typeof GatewaySignUpIndexRoute
  ApiBaseResumeIndexRoute: typeof ApiBaseResumeIndexRoute
  ApiTailoredResumesIndexRoute: typeof ApiTailoredResumesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tailored-resumes/': {
      id: '/api/tailored-resumes/'
      path: '/api/tailored-resumes'
      fullPath: '/api/tailored-resumes/'
      preLoaderRoute: typeof ApiTailoredResumesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/base-resume/': {
      id: '/api/base-resume/'
      path: '/api/base-resume'
      fullPath: '/api/base-resume/'
      preLoaderRoute: typeof ApiBaseResumeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gateway/sign-up/': {
      id: '/_gateway/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof GatewaySignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gateway/sign-in/': {
      id: '/_gateway/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof GatewaySignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/tailored-resumes/$sessionId': {
      id: '/api/tailored-resumes/$sessionId'
      path: '/api/tailored-resumes/$sessionId'
      fullPath: '/api/tailored-resumes/$sessionId'
      preLoaderRoute: typeof ApiTailoredResumesSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resumes/$reportId': {
      id: '/api/resumes/$reportId'
      path: '/api/resumes/$reportId'
      fullPath: '/api/resumes/$reportId'
      preLoaderRoute: typeof ApiResumesReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/base-resume/$resumeId': {
      id: '/api/base-resume/$resumeId'
      path: '/api/base-resume/$resumeId'
      fullPath: '/api/base-resume/$resumeId'
      preLoaderRoute: typeof ApiBaseResumeResumeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/verify-otp': {
      id: '/api/auth/verify-otp'
      path: '/api/auth/verify-otp'
      fullPath: '/api/auth/verify-otp'
      preLoaderRoute: typeof ApiAuthVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-up': {
      id: '/api/auth/sign-up'
      path: '/api/auth/sign-up'
      fullPath: '/api/auth/sign-up'
      preLoaderRoute: typeof ApiAuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in': {
      id: '/api/auth/sign-in'
      path: '/api/auth/sign-in'
      fullPath: '/api/auth/sign-in'
      preLoaderRoute: typeof ApiAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tailored-resumes/$sessionId/': {
      id: '/_app/tailored-resumes/$sessionId/'
      path: '/tailored-resumes/$sessionId'
      fullPath: '/tailored-resumes/$sessionId/'
      preLoaderRoute: typeof AppTailoredResumesSessionIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tailored-resumes/$sessionId/preview/': {
      id: '/_app/tailored-resumes/$sessionId/preview/'
      path: '/tailored-resumes/$sessionId/preview'
      fullPath: '/tailored-resumes/$sessionId/preview/'
      preLoaderRoute: typeof AppTailoredResumesSessionIdPreviewIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppTailoredResumesSessionIdIndexRoute: typeof AppTailoredResumesSessionIdIndexRoute
  AppTailoredResumesSessionIdPreviewIndexRoute: typeof AppTailoredResumesSessionIdPreviewIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppTailoredResumesSessionIdIndexRoute: AppTailoredResumesSessionIdIndexRoute,
  AppTailoredResumesSessionIdPreviewIndexRoute:
    AppTailoredResumesSessionIdPreviewIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiAuthSignInRoute: ApiAuthSignInRoute,
  ApiAuthSignUpRoute: ApiAuthSignUpRoute,
  ApiAuthVerifyOtpRoute: ApiAuthVerifyOtpRoute,
  ApiBaseResumeResumeIdRoute: ApiBaseResumeResumeIdRoute,
  ApiResumesReportIdRoute: ApiResumesReportIdRoute,
  ApiTailoredResumesSessionIdRoute: ApiTailoredResumesSessionIdRoute,
  GatewaySignInIndexRoute: GatewaySignInIndexRoute,
  GatewaySignUpIndexRoute: GatewaySignUpIndexRoute,
  ApiBaseResumeIndexRoute: ApiBaseResumeIndexRoute,
  ApiTailoredResumesIndexRoute: ApiTailoredResumesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
