/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as GatewayIndexRouteImport } from './routes/_gateway/index'
import { Route as AppEnhanceResumeIndexRouteImport } from './routes/_app/enhance-resume/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const GatewayIndexRoute = GatewayIndexRouteImport.update({
  id: '/_gateway/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEnhanceResumeIndexRoute = AppEnhanceResumeIndexRouteImport.update({
  id: '/enhance-resume/',
  path: '/enhance-resume/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof GatewayIndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/enhance-resume/': typeof AppEnhanceResumeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof GatewayIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/enhance-resume': typeof AppEnhanceResumeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_gateway/': typeof GatewayIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/enhance-resume/': typeof AppEnhanceResumeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard/' | '/enhance-resume/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/enhance-resume'
  id:
    | '__root__'
    | '/_app'
    | '/_gateway/'
    | '/_app/dashboard/'
    | '/_app/enhance-resume/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  GatewayIndexRoute: typeof GatewayIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gateway/': {
      id: '/_gateway/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GatewayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/enhance-resume/': {
      id: '/_app/enhance-resume/'
      path: '/enhance-resume'
      fullPath: '/enhance-resume/'
      preLoaderRoute: typeof AppEnhanceResumeIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppEnhanceResumeIndexRoute: typeof AppEnhanceResumeIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppEnhanceResumeIndexRoute: AppEnhanceResumeIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  GatewayIndexRoute: GatewayIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
